version: '3.8'

services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
        T: 100
    container_name: jenkins
    environment:
      TZ: "Asia/Seoul"
      DOCKER_GID: ${DOCKER_GID}
      JAVA_OPTS: "-Dhudson.model.DownloadService.noSignatureCheck=true"

    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

