FROM jenkins/jenkins:latest
ARG DOCKER_GID
USER root


# docker install
COPY sh/docker.sh /docker.sh
RUN chmod +x /docker.sh && \
    /docker.sh

# set jenkins user to host docker group
RUN groupadd -g ${DOCKER_GID} -f docker && \
    usermod -aG docker jenkins

USER jenkins