version: '3.9'

services:
  jenkins:
    build:
      context: .
      args:
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID}
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
      - DOCKER_GROUP_ID=${DOCKER_GROUP_ID}

    ports:
      - 8080:8080
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock